import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
page.setDefaultTimeout(15000);
await page.goto('http://localhost:4321', { waitUntil: 'networkidle' });
await page.click('.studio-pages-table tbody tr:has-text("LuckyBet DE")');
await page.waitForSelector('.studio-el-panel');
await page.waitForTimeout(800);
await page.screenshot({ path: 'shots/el-default.png' });
await page.click('h1.hero-title');
await page.waitForSelector('.studio-el-meta, .studio-inspector textarea');
await page.screenshot({ path: 'shots/el-selected.png' });
await page.click('.studio-el-iconbtn[title="Back"]');
await page.click('.studio-el-tabs button:text("Page")');
await page.waitForSelector('.studio-seo');
await page.waitForTimeout(1000);
await page.screenshot({ path: 'shots/el-page-tab.png' });
await page.click('.studio-el-iconbtn[title="Preview"]');
await page.waitForSelector('.studio-el-exit-preview');
await page.waitForTimeout(600);
await page.screenshot({ path: 'shots/el-preview.png' });
await browser.close();
console.log('done');
